#!/usr/bin/env python

import logging

log_level = logging.DEBUG

REFRESH_STATUS_GET_CURRENT_STATUS = 0
REFRESH_STATUS_GET_NOTIFICATION = 1
REFRESH_STATUS_GET_COMMENTS = 2
REFRESH_STATUS_GET_USERS_ICON = 3
REFRESH_STATUS_GET_APPS_ICON = 4
REFRESH_STATUS_COMPLETED = 5

IS_LOGIN = 0
REFRESHING = 1
WAITING_LOGIN = 2
NO_LOGIN = 3

